<<<<<<< HEAD
analyzer:
  errors:
    depend_on_referenced_packages: ignore ignore
    use_build_context_synchronously: ignore
    use_build_context_synchronously: ignore
=======
>>>>>>> 4ad3876e6bc5a6194832929fb87acb974b9ff17e
include: package:flutter_lints/flutter.yaml

linter:
  rules:
    avoid_print: false
    prefer_const_constructors_in_immutables: false
    prefer_const_constructors: false
    prefer_const_literals_to_create_immutables: false
    prefer_final_fields: false
    unnecessary_breaks: true
    use_key_in_widget_constructors: false
